<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Tests" tests="7" skipped="0" failures="1" errors="0" timestamp="2019-12-29T03:10:01" hostname="DESKTOP-R0R2739" time="0.038">
  <properties/>
  <testcase name="testSolutionWithValidArrayContainingSomeNulls" classname="Tests" time="0.015"/>
  <testcase name="testSolutionWithValidArrayContainingAllPalindromes" classname="Tests" time="0.003"/>
  <testcase name="testSolutionWithValidArrayContainingNumericPalindromes" classname="Tests" time="0.008">
    <failure message="java.lang.AssertionError: array lengths differed, expected.length=3 actual.length=4" type="java.lang.AssertionError">java.lang.AssertionError: array lengths differed, expected.length=3 actual.length=4
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.internal.ComparisonCriteria.assertArraysAreSameLength(ComparisonCriteria.java:76)
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:37)
	at org.junit.Assert.internalArrayEquals(Assert.java:532)
	at org.junit.Assert.assertArrayEquals(Assert.java:283)
	at org.junit.Assert.assertArrayEquals(Assert.java:298)
	at Tests.testSolutionWithValidArrayContainingNumericPalindromes(Tests.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
</failure>
  </testcase>
  <testcase name="testSolutionWithValidArrayContainingSomePalindromes" classname="Tests" time="0.002"/>
  <testcase name="testSolutionWithEmptyArray" classname="Tests" time="0.0"/>
  <testcase name="testSolutionWithValidArrayContainingNoPalindromes" classname="Tests" time="0.002"/>
  <testcase name="testSolutionWithNullArray" classname="Tests" time="0.002"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
