<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Tests" tests="5" skipped="0" failures="1" errors="0" timestamp="2019-12-31T02:33:09" hostname="LAPTOP-F0S6CQ8O" time="0.02">
  <properties/>
  <testcase name="testSolutionWithReversedArray" classname="Tests" time="0.013"/>
  <testcase name="testSolutionWithPresortedArray" classname="Tests" time="0.001"/>
  <testcase name="testSolutionWithEmptyArray" classname="Tests" time="0.0"/>
  <testcase name="testSolutionWithRandomArray" classname="Tests" time="0.001"/>
  <testcase name="testSolutionWithNullArray" classname="Tests" time="0.003">
    <failure message="java.lang.NullPointerException" type="java.lang.NullPointerException">java.lang.NullPointerException
	at Task.sortNumbers(Task.java:10)
	at Tests.testSolutionWithNullArray(Tests.java:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
</failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
