<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Tests" tests="7" skipped="0" failures="1" errors="0" timestamp="2019-12-31T07:13:19" hostname="MSI" time="0.024">
  <properties/>
  <testcase name="testCountWordsWithEmptyStringArray" classname="Tests" time="0.006"/>
  <testcase name="testExtractTextWithExistingFileContainingText" classname="Tests" time="0.011">
    <failure message="java.lang.AssertionError: array lengths differed, expected.length=9 actual.length=10" type="java.lang.AssertionError">java.lang.AssertionError: array lengths differed, expected.length=9 actual.length=10
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.internal.ComparisonCriteria.assertArraysAreSameLength(ComparisonCriteria.java:76)
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:37)
	at org.junit.Assert.internalArrayEquals(Assert.java:532)
	at org.junit.Assert.assertArrayEquals(Assert.java:283)
	at org.junit.Assert.assertArrayEquals(Assert.java:298)
	at Tests.testExtractTextWithExistingFileContainingText(Tests.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
</failure>
  </testcase>
  <testcase name="testCountWordsWithValidStringArray" classname="Tests" time="0.001"/>
  <testcase name="testExtractTextWithNullFile" classname="Tests" time="0.001"/>
  <testcase name="testExtractTextWithMissingFile" classname="Tests" time="0.001"/>
  <testcase name="testCountWordsWithNullStringArray" classname="Tests" time="0.0"/>
  <testcase name="testExtractTextWithExistingEmptyFile" classname="Tests" time="0.001"/>
  <system-out><![CDATA[the quick brown fox jumped over the lazy dog
An exception occured
Exception thrown while reading the file
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
